#ifndef CONST_VARIABLE_HPP
#define CONST_VARIABLE_HPP

enum {
	USERNAME_LEN = 25,
	PASSWORD_LEN = 35,
	NAME_LEN = 20,
	MAIL_ADDR_LEN = 35,
	TRAIN_ID_LEN = 25,
	STATION_LEN = 40,
	STATION_NUM_MAX = 102,
	DATE_MAX = 100,
	STATUS_SUCCESS = 1,
	STATUS_PENDING = 2,
	STATUS_REFUNDED = 3
};

#endif // CONST_VARIABLE_HPP
